# Generated by Django 6.0.7 on 2026-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_driver_approval_status_driver_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik (Latitude)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik (Longitude)'),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Masofa (km)'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Qayerdan Kenglik (Lat)'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Qayerdan Uzunlik (Lng)'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Qayerga Kenglik (Lat)'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Qayerga Uzunlik (Lng)'),
        ),
    ]
