# Generated by Django 6.0.7 on 2026-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_driver_latitude_driver_longitude_order_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balans'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Komissiya (har bir zakaz uchun)'),
        ),
    ]
