# Generated by Django 6.0.7 on 2026-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_driver_balance_order_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=5000, help_text='Har bir buyurtma uchun minimal narx', max_digits=10, verbose_name="Boshlang'ich narx (UZS)")),
                ('price_per_km', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='1 km narxi (UZS)')),
                ('commission', models.DecimalField(decimal_places=2, default=1000, help_text='Har bir qabul qilingan buyurtma uchun haydovchi balansidan yechiladi', max_digits=10, verbose_name='Haydovchi komissiyasi (UZS)')),
                ('auto_dispatch', models.BooleanField(default=True, help_text="Yoqilgan bo'lsa eng yaqin haydovchiga avtomatik beriladi", verbose_name='Avtomatik taqsimlash')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tariff sozlamalari',
                'verbose_name_plural': 'Tariff sozlamalari',
            },
        ),
    ]
