# Generated by Django 6.0.7 on 2026-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_add_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_address',
            field=models.CharField(max_length=255, verbose_name='Mijoz manzili'),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Manzil Kenglik (Lat)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Manzil Uzunlik (Lng)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Qayerga (ixtiyoriy)'),
        ),
    ]
