# Generated by Django 6.0.7 on 2026-07-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_make_to_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to='taxi.driver', verbose_name='Yuborilgan haydovchi'),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_orders', to='taxi.driver', verbose_name='Rad etgan haydovchilar'),
        ),
    ]
