# Generated by Django 6.0.7 on 2026-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_add_dispatch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti'),
        ),
        migrations.AddField(
            model_name='tariffsettings',
            name='dispatch_timeout',
            field=models.IntegerField(default=10, help_text='Har bir haydovchi qabul qilishi uchun beriladigan vaqt', verbose_name='Kutish vaqti (sekund)'),
        ),
        migrations.AddField(
            model_name='tariffsettings',
            name='max_dispatch_attempts',
            field=models.IntegerField(default=4, help_text="Buyurtma eng ko'pi bilan nechta haydovchiga navbatma-navbat ko'rsatiladi", verbose_name='Maksimal urinishlar soni'),
        ),
    ]
