# Generated by Django 6.0.7 on 2026-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_order_dispatched_at_tariffsettings_dispatch_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('nominatim', 'OpenStreetMap (Nominatim) — Bepul'), ('yandex', 'Yandex Geocoder'), ('geoapify', 'Geoapify'), ('google', 'Google Maps')], default='nominatim', max_length=20, verbose_name='Geocoding API')),
                ('api_key', models.CharField(blank=True, default='', help_text='Nominatim uchun shart emas', max_length=255, verbose_name='API kalit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maps sozlamalari',
                'verbose_name_plural': 'Maps sozlamalari',
            },
        ),
    ]
