# Generated by Django 6.0.7 on 2026-07-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0015_client_rating_driver_destination_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='client_bot_token',
            field=models.CharField(blank=True, default='', help_text='Mijozlar buyurtma beruvchi bot tokeni', max_length=200, verbose_name='Mijoz Bot Token'),
        ),
    ]
