# Generated by Django 6.0.7 on 2026-07-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0016_add_client_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Manzil')),
                ('note', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('viewed', "Ko'rildi"), ('resolved', 'Hal qilindi')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim hal qildi')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='taxi.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'SOS signal',
                'verbose_name_plural': 'SOS signallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
