# Generated by Django 6.0.7 on 2026-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0017_add_sos_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='extra_group_ids',
            field=models.TextField(blank=True, default='', help_text="Har bir ID yangi qatorda. Bot qo'shilgan barcha guruhlarga yuboradi.", verbose_name="Qo'shimcha guruh IDlar"),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='group_id',
            field=models.CharField(blank=True, default='', help_text='Birinchi operatorlar guruhi chat_id', max_length=50, verbose_name='Asosiy Guruh Chat ID'),
        ),
    ]
