# Generated by Django 4.2.16 on 2026-07-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0020_add_tmx_dist_km'),
        ('taxi', '0021_driver_rating_order_client_rating'),
    ]

    operations = [
    ]
