# Generated by Django 4.2.16 on 2026-07-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0022_merge_20260717_0922'),
        ('taxi', '0022_merge_tmx_and_rating'),
    ]

    operations = [
    ]
