# Generated by Django 4.2.16 on 2026-07-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0023_add_tmx_fields'),
        ('taxi', '0023_merge_20260717_0923'),
    ]

    operations = [
    ]
