# Generated by Django 4.2.16 on 2026-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0024_merge_0023_add_tmx_fields_0023_merge_20260717_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tmx_dist_km',
            field=models.FloatField(default=0, verbose_name='Taximetr masofa (km)'),
        ),
    ]
