# Generated by Django 4.2.16 on 2026-07-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0024_driver_last_seen'),
        ('taxi', '0025_alter_order_tmx_dist_km'),
    ]

    operations = [
    ]
