# Generated by Django 4.2.16 on 2026-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0026_merge_20260717_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name="So'nggi manzil"),
        ),
    ]
