# Generated by Django 4.2.16 on 2026-07-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0027_driver_last_address'),
        ('taxi', '0028_client_is_blocked'),
    ]

    operations = [
    ]
