# Generated by Django 4.2.16 on 2026-07-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0029_balance_log'),
        ('taxi', '0029_merge_0027_driver_last_address_0028_client_is_blocked'),
    ]

    operations = [
    ]
