# Generated by Django 4.2.16 on 2026-07-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0030_chatmessage_audio'),
        ('taxi', '0030_merge_20260717_1206'),
    ]

    operations = [
    ]
