# Generated by Django 4.2.16 on 2026-07-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0031_add_group_message'),
        ('taxi', '0031_merge_0030_chatmessage_audio_0030_merge_20260717_1206'),
    ]

    operations = [
    ]
