# Generated by Django 4.2.16 on 2026-07-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0032_groupmessage_operator_support'),
        ('taxi', '0032_merge_20260717_1314'),
    ]

    operations = [
    ]
