# Generated by Django 6.0.7 on 2026-07-19 03:41

from django.db import migrations, models


def seed_panel_sounds(apps, schema_editor):
    """Har bir hodisa kaliti uchun standart (yoqilgan, faylsiz) qator yaratadi —
    shunday qilib sound_settings sahifasi ochilishidan oldin ham standart ohanglar ishlaydi."""
    from taxi.constants import PANEL_SOUND_EVENTS, DRIVER_SOUND_EVENTS
    PanelSound = apps.get_model('taxi', 'PanelSound')
    for key, _label in PANEL_SOUND_EVENTS + DRIVER_SOUND_EVENTS:
        PanelSound.objects.get_or_create(event_key=key)


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0034_driver_last_address_and_tmx_dist_km_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('panel_new_order', '🚨 Yangi buyurtma'), ('panel_order_deleted', "🗑 Buyurtma o'chirildi"), ('panel_order_cancelled', '❌ Buyurtma bekor qilindi'), ('panel_order_rejected', '🔄 Buyurtma rad etildi'), ('panel_driver_registered', "🆕 Yangi haydovchi qo'shildi"), ('panel_sos_alert', '🆘 SOS signal')], max_length=30, verbose_name='Hodisa turi')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Panel hodisasi',
                'verbose_name_plural': 'Panel hodisalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('panel_new_order', '🚨 Yangi buyurtma'), ('panel_order_deleted', "🗑 Buyurtma o'chirildi"), ('panel_order_cancelled', '❌ Buyurtma bekor qilindi'), ('panel_order_rejected', '🔄 Buyurtma rad etildi'), ('panel_driver_registered', "🆕 Yangi haydovchi qo'shildi"), ('panel_sos_alert', '🆘 SOS signal'), ('driver_new_order', '🚨 Yangi buyurtma'), ('driver_accept', '✅ Buyurtma qabul qilindi'), ('driver_reject', '❌ Rad etish / bekor qilish'), ('driver_complete', '🏁 Buyurtma yakunlandi'), ('driver_online', '🟢 Navbatga kirdi'), ('driver_offline', '🔴 Navbatdan chiqdi')], max_length=30, unique=True, verbose_name='Hodisa')),
                ('file', models.FileField(blank=True, null=True, upload_to='sounds/', verbose_name='Audio fayl')),
                ('enabled', models.BooleanField(default=True, verbose_name='Yoqilgan')),
            ],
            options={
                'verbose_name': 'Ovoz sozlamasi',
                'verbose_name_plural': 'Ovoz sozlamalari',
            },
        ),
        migrations.RunPython(seed_panel_sounds, migrations.RunPython.noop),
    ]
