# Generated by Django 4.2.16 on 2026-07-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0033_merge_20260717_1328'),
        ('taxi', '0034_driver_last_address_and_tmx_dist_km_fix'),
    ]

    operations = [
    ]
