# Generated by Django 4.2.16 on 2026-07-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0035_merge_20260718_0923'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='taxi_order_status_e06106_idx',
            old_name='taxi_order_status_driver_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='taxi_order_status_af94ec_idx',
            old_name='taxi_order_status_dispatch_idx',
        ),
    ]
