# Generated by Django 4.2.16 on 2026-07-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0035_panelevent_panelsound'),
        ('taxi', '0036_rename_taxi_order_status_driver_idx_taxi_order_status_e06106_idx_and_more'),
    ]

    operations = [
    ]
