# Generated by Django 6.0.7 on 2026-07-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0036_more_sound_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsettings',
            name='waiting_price_per_minute',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Haydovchi "Kutish" tugmasini bosgan vaqtda, har daqiqa uchun qo\'shiladigan narx', max_digits=10, verbose_name='Kutish narxi (1 daqiqa, UZS)'),
        ),
    ]
