# Generated by Django 4.2.16 on 2026-07-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0036_more_sound_events'),
        ('taxi', '0037_merge_20260719_0925'),
    ]

    operations = [
    ]
