# Generated by Django 6.0.7 on 2026-07-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0037_tariff_waiting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsettings',
            name='operator_phone',
            field=models.CharField(default='1351', help_text="Haydovchi qabul qilingan buyurtmani bekor qilmoqchi bo'lsa, shu raqamga qo'ng'iroq qiladi", max_length=20, verbose_name='Operator telefon raqami'),
        ),
    ]
