# Generated by Django 6.0.7 on 2026-07-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0038_tariff_operator_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_type',
            field=models.CharField(choices=[('light', '🚗 Yengil'), ('cargo', '🚚 Yuk mashinasi'), ('minivan', '🚐 Minivan')], default='light', max_length=10, verbose_name='Mashina turi'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_type',
            field=models.CharField(choices=[('light', '🚗 Yengil'), ('cargo', '🚚 Yuk mashinasi'), ('minivan', '🚐 Minivan')], default='light', max_length=10, verbose_name='Mashina turi'),
        ),
    ]
