# Generated by Django 4.2.16 on 2026-07-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0037_tariff_waiting_price'),
        ('taxi', '0038_merge_0036_more_sound_events_0037_merge_20260719_0925'),
    ]

    operations = [
    ]
