# Generated by Django 6.0.7 on 2026-07-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0039_add_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Efirdagi haydovchi',
                'verbose_name_plural': 'Efirdagi haydovchilar',
            },
        ),
        migrations.CreateModel(
            name='VoiceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE Candidate'), ('leave', 'Leave')], max_length=12, verbose_name='Turi')),
                ('payload', models.TextField(blank=True, default='', verbose_name="Ma'lumot (JSON)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Ovoz signali',
                'verbose_name_plural': 'Ovoz signallari',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='voiceparticipant',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_participant', to='taxi.driver', verbose_name='Haydovchi'),
        ),
        migrations.AddField(
            model_name='voicesignal',
            name='from_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_signals_sent', to='taxi.driver', verbose_name='Kimdan'),
        ),
        migrations.AddField(
            model_name='voicesignal',
            name='to_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_signals_received', to='taxi.driver', verbose_name='Kimga'),
        ),
        migrations.AddIndex(
            model_name='voicesignal',
            index=models.Index(fields=['to_driver', 'created_at'], name='taxi_voices_to_driv_aa9b61_idx'),
        ),
    ]
