# Generated by Django 4.2.16 on 2026-07-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0038_tariff_operator_phone'),
        ('taxi', '0039_merge_20260719_1029'),
    ]

    operations = [
    ]
