# Generated by Django 6.0.7 on 2026-07-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0040_voiceparticipant_voicesignal_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='taxi_order_status_e06106_idx',
            old_name='taxi_order_status_driver_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='taxi_order_status_af94ec_idx',
            old_name='taxi_order_status_dispatch_idx',
        ),
    ]
