# Generated by Django 4.2.16 on 2026-07-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0039_add_car_type'),
        ('taxi', '0040_merge_20260719_1304'),
    ]

    operations = [
    ]
