# Generated by Django 4.2.16 on 2026-07-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0040_voiceparticipant_voicesignal_and_more'),
        ('taxi', '0041_merge_0039_add_car_type_0040_merge_20260719_1304'),
    ]

    operations = [
    ]
