# Generated by Django 4.2.16 on 2026-07-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0041_rename_taxi_order_status_driver_idx_taxi_order_status_e06106_idx_and_more'),
        ('taxi', '0042_merge_20260720_1156'),
    ]

    operations = [
    ]
