# Generated by Django 6.0.7 on 2026-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0043_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='Telegram Chat ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Ism (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Bot admin',
                'verbose_name_plural': 'Bot adminlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
