# Generated by Django 6.0.7 on 2026-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0043_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='admin_chat_ids',
            field=models.TextField(blank=True, default='', help_text="Operator bot orqali buyurtma yaratish va boshqarish huquqiga ega shaxsiy Telegram ID'lar. Har biri yangi qatorda.", verbose_name="Admin Telegram ID'lar"),
        ),
    ]
