# Generated by Django 6.0.7 on 2026-07-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0045_seed_bot_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="So'ralgan summa")),
                ('receipt', models.ImageField(upload_to='topup_receipts/', verbose_name='Chek rasmi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqti')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to='taxi.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': "Balans to'ldirish so'rovi",
                'verbose_name_plural': "Balans to'ldirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
