# Generated by Django 6.0.7 on 2026-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0046_balancetopuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='notify_low_balance',
            field=models.BooleanField(default=True, verbose_name='Balans kam ogohlantirish'),
        ),
    ]
