# Generated by Django 4.2.16 on 2026-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0047_botsettings_notify_low_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelevent',
            name='event_type',
            field=models.CharField(choices=[('panel_new_order', '🚨 Yangi buyurtma'), ('panel_order_deleted', "🗑 Buyurtma o'chirildi"), ('panel_order_cancelled', '❌ Buyurtma bekor qilindi'), ('panel_order_rejected', '🔄 Buyurtma rad etildi'), ('panel_order_completed', '🏁 Buyurtma yakunlandi'), ('panel_order_on_way', "🚗 Haydovchi yo'lda"), ('panel_order_arrived', '📍 Haydovchi yetib keldi'), ('panel_driver_registered', "🆕 Yangi haydovchi qo'shildi"), ('panel_driver_approved', '✅ Haydovchi tasdiqlandi'), ('panel_driver_rejected', '🚫 Haydovchi rad etildi'), ('panel_driver_blocked', '🔒 Haydovchi bloklandi/ochildi'), ('panel_balance_changed', "💰 Balans o'zgardi"), ('panel_low_balance', '⚠️ Balans kam'), ('panel_topup_request', "💳 Balans to'ldirish so'rovi"), ('panel_sos_alert', '🆘 SOS signal')], max_length=30, verbose_name='Hodisa turi'),
        ),
        migrations.AlterField(
            model_name='panelsound',
            name='event_key',
            field=models.CharField(choices=[('panel_new_order', '🚨 Yangi buyurtma'), ('panel_order_deleted', "🗑 Buyurtma o'chirildi"), ('panel_order_cancelled', '❌ Buyurtma bekor qilindi'), ('panel_order_rejected', '🔄 Buyurtma rad etildi'), ('panel_order_completed', '🏁 Buyurtma yakunlandi'), ('panel_order_on_way', "🚗 Haydovchi yo'lda"), ('panel_order_arrived', '📍 Haydovchi yetib keldi'), ('panel_driver_registered', "🆕 Yangi haydovchi qo'shildi"), ('panel_driver_approved', '✅ Haydovchi tasdiqlandi'), ('panel_driver_rejected', '🚫 Haydovchi rad etildi'), ('panel_driver_blocked', '🔒 Haydovchi bloklandi/ochildi'), ('panel_balance_changed', "💰 Balans o'zgardi"), ('panel_low_balance', '⚠️ Balans kam'), ('panel_topup_request', "💳 Balans to'ldirish so'rovi"), ('panel_sos_alert', '🆘 SOS signal'), ('driver_new_order', '🚨 Yangi buyurtma'), ('driver_accept', '✅ Buyurtma qabul qilindi'), ('driver_reject', '❌ Rad etish / bekor qilish'), ('driver_complete', '🏁 Buyurtma yakunlandi'), ('driver_online', '🟢 Navbatga kirdi'), ('driver_offline', '🔴 Navbatdan chiqdi'), ('driver_chat_message', '💬 Yangi chat xabari'), ('driver_balance_changed', "💰 Balans to'ldirildi")], max_length=30, unique=True, verbose_name='Hodisa'),
        ),
    ]
