# Generated by Django 6.0.7 on 2026-07-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0048_alter_panelevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='operator_typing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Operator yozayotgan vaqt'),
        ),
    ]
