# Generated by Django 6.0.7 on 2026-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0049_driver_operator_typing_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', help_text='Eskiz.uz kabinetiga kirish emaili', max_length=255, verbose_name='Eskiz Email')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Eskiz Parol')),
                ('nickname', models.CharField(blank=True, default='4546', help_text="Eskiz'da tasdiqlangan alfa-nom. Test rejimida 4546", max_length=50, verbose_name='Sender nomi (nickname)')),
                ('token', models.TextField(blank=True, default='', verbose_name='Auth token (avtomatik)')),
                ('token_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Token yangilangan vaqt')),
                ('sms_accepted', models.BooleanField(default=True, verbose_name='Buyurtma qabul qilindi')),
                ('sms_arrived', models.BooleanField(default=True, verbose_name='Haydovchi yetib keldi')),
                ('sms_completed', models.BooleanField(default=True, verbose_name='Buyurtma yakunlandi')),
                ('sms_cancelled', models.BooleanField(default=True, verbose_name='Buyurtma bekor qilindi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS sozlamalari',
                'verbose_name_plural': 'SMS sozlamalari',
            },
        ),
    ]
