# Generated by Django 6.0.7 on 2026-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0050_smssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', help_text='platform.openai.com dan olingan sk-... kalit', max_length=255, verbose_name='OpenAI API kalit')),
                ('model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o mini (tez va arzon)'), ('gpt-4o', 'GPT-4o')], default='gpt-4o-mini', max_length=50, verbose_name='Model')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI sozlamalari',
                'verbose_name_plural': 'AI sozlamalari',
            },
        ),
    ]
