# Generated by Django 6.0.7 on 2026-07-25 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0051_aisettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('driver', 'Haydovchi'), ('client', 'Mijoz')], max_length=10)),
                ('period', models.CharField(max_length=7, verbose_name='Davr (YYYY-MM)')),
                ('reward_text', models.TextField(blank=True, default='', verbose_name="Sovg'a tavsifi")),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_rewards', to='taxi.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_rewards', to='taxi.driver')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "AI sovg'a tarixi",
                'verbose_name_plural': "AI sovg'a tarixi",
                'constraints': [models.UniqueConstraint(fields=('reward_type', 'driver', 'period'), name='unique_driver_reward_per_period'), models.UniqueConstraint(fields=('reward_type', 'client', 'period'), name='unique_client_reward_per_period')],
            },
        ),
    ]
