# Generated by Django 6.0.7 on 2026-07-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0053_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Haydovchi shartnomasi', max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(default='VIJDON TAXI SERVISI BILAN HAYDOVCHI O\'RTASIDA TUZILADIGAN SHARTNOMA\n\n1. UMUMIY QOIDALAR\n1.1. Ushbu shartnoma "Vijdon Taxi" xizmati (bundan buyon — Kompaniya) bilan platformaga ro\'yxatdan o\'tgan haydovchi (bundan buyon — Haydovchi) o\'rtasidagi hamkorlik shartlarini belgilaydi.\n1.2. Haydovchi ushbu shartnoma shartlarini to\'liq o\'qib chiqqach, ilova orqali elektron imzo qo\'yish yo\'li bilan shartnoma shartlariga rozilik bildiradi. Elektron imzo qog\'ozdagi imzo bilan teng huquqiy kuchga ega.\n1.3. Haydovchi Kompaniyaning shtatdagi xodimi emas, balki mustaqil hamkor sifatida buyurtmalarni bajaradi.\n\n2. HAYDOVCHIGA QO\'YILADIGAN TALABLAR\n2.1. Haydovchida amaldagi haydovchilik guvohnomasi, transport vositasi esa texnik ko\'rikdan o\'tgan va sug\'urtalangan bo\'lishi shart.\n2.2. Haydovchi mashinani toza va ishlaydigan holatda saqlashi, buyurtmani belgilangan vaqtda qabul qilishi shart.\n2.3. Yo\'lovchilar bilan xushmuomala, hurmatli munosabatda bo\'lish, haydash chog\'ida telefon bilan chalg\'imaslik, tezlik chegaralariga va yo\'l harakati qoidalariga qat\'iy rioya qilish majburiy.\n2.4. Ish vaqtida spirtli ichimlik yoki boshqa mast qiluvchi vositalar iste\'mol qilish qat\'iyan taqiqlanadi — bunday holat aniqlansa, Haydovchi platformadan darhol va butunlay chetlashtiriladi.\n\n3. BUYURTMALAR VA TO\'LOVLAR\n3.1. Buyurtmalar tizim orqali avtomatik taqsimlanadi, Haydovchi sababsiz buyurtmani tez-tez rad etmasligi lozim.\n3.2. Har bir yakunlangan buyurtmadan tizim komissiyasi joriy tarif sozlamalariga muvofiq ushlab qolinadi.\n3.3. Haydovchi balansi manfiy bo\'lib qolgan taqdirda yangi buyurtmalar qabul qila olmaydi, balansni ilova orqali o\'z vaqtida to\'ldirishi lozim.\n\n4. JARIMALAR VA CHEKLOVLAR\n4.1. Sababsiz buyurtmani bekor qilish, mijozdan qo\'shimcha pul talab qilish, buyurtmani chetlab o\'tish kabi holatlar aniqlansa, Kompaniya Haydovchiga ogohlantirish berish, vaqtinchalik yoki butunlay platformadan chetlashtirish huquqiga ega.\n4.2. Mijozlar tomonidan takroran asosli shikoyatlar tushgan taqdirda Kompaniya Haydovchi profilini ko\'rib chiqadi va tegishli chora ko\'radi.\n\n5. MAXFIYLIK\n5.1. Haydovchi buyurtma davomida olingan mijoz ma\'lumotlarini (telefon raqami, manzili va h.k.) faqat buyurtmani bajarish maqsadida ishlatishi, uchinchi shaxslarga bermasligi shart.\n\n6. SHARTNOMANI BEKOR QILISH\n6.1. Har ikki tomon istalgan vaqtda hamkorlikni to\'xtatishi mumkin — Haydovchi profilini o\'chirish yoki faoliyatsizlantirish orqali.\n6.2. Kompaniya ushbu qoidalarni jiddiy buzgan Haydovchini oldindan ogohlantirmasdan platformadan chetlashtirish huquqini o\'zida saqlab qoladi.\n\n7. MAS\'ULIYAT\n7.1. Yo\'l harakati qoidalarini buzish, transport vositasining texnik holati va yo\'l-transport hodisalari yuzasidan to\'liq mas\'uliyat Haydovchi zimmasida bo\'ladi.\n7.2. Kompaniya faqat buyurtmalarni taqsimlovchi platforma bo\'lib, tomonlar o\'rtasidagi nizolarni imkon qadar adolatli hal qilishga ko\'maklashadi.\n\n8. YAKUNIY QOIDALAR\n8.1. Ushbu shartnoma matni Kompaniya tomonidan yangilanishi mumkin — yangilangan taqdirda Haydovchidan shartnomani qayta ko\'rib chiqib, qayta imzolashi so\'raladi.\n8.2. Elektron imzo qo\'yish orqali Haydovchi yuqoridagi barcha shartlarni o\'qigan, tushungan va ularga to\'liq rozi ekanligini tasdiqlaydi.\n\nEslatma: ushbu matn namunaviy hamkorlik shartnomasi bo\'lib, joriy qonunchilikka moslashtirish uchun yurist bilan maslahatlashish tavsiya etiladi.', verbose_name='Shartnoma matni')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiya')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shartnoma sozlamalari',
                'verbose_name_plural': 'Shartnoma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='DriverContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=255, verbose_name="Imzolagan payt to'liq ismi")),
                ('signature', models.ImageField(upload_to='signatures/', verbose_name='Imzo rasmi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to='taxi.driver')),
            ],
            options={
                'verbose_name': 'Shartnoma imzosi',
                'verbose_name_plural': 'Shartnoma imzolari',
                'ordering': ['-signed_at'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'version'), name='unique_driver_contract_version')],
            },
        ),
    ]
