# Generated by Django 6.0.7 on 2026-07-25 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0055_alter_contractsettings_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Kod')),
                ('amount', models.DecimalField(decimal_places=0, default=3000, max_digits=10, verbose_name='Chegirma summasi')),
                ('batch_note', models.CharField(blank=True, default='', max_length=100, verbose_name='Partiya izohi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyer_vouchers', to='taxi.driver')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flayer kuponi',
                'verbose_name_plural': 'Flayer kuponlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
