# Generated by Django 6.0.7 on 2026-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0056_flyervoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='driver_extra_group_ids',
            field=models.TextField(blank=True, default='', help_text='Har bir ID yangi qatorda', verbose_name="Qo'shimcha haydovchilar guruhlari"),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='driver_group_id',
            field=models.CharField(blank=True, default='', help_text='Yangi buyurtmalar shu guruhga ham yuboriladi — mijoz telefon raqamisiz', max_length=50, verbose_name='Haydovchilar Guruhi Chat ID'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_driver_group',
            field=models.BooleanField(default=True, verbose_name='Haydovchilar guruhiga yuborish'),
        ),
    ]
