# Generated by Django 6.0.7 on 2026-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0057_botsettings_driver_extra_group_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='notify_evening_top_drivers',
            field=models.BooleanField(default=True, verbose_name='Kechqurungi TOP-10 haydovchilar'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_morning_greeting',
            field=models.BooleanField(default=True, verbose_name='Ertalabki salomlashuv'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_night_greeting',
            field=models.BooleanField(default=True, verbose_name='Tungi navbatchilarga salom'),
        ),
    ]
