# Generated by Django 6.0.7 on 2026-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0058_botsettings_notify_evening_top_drivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='last_evening_top_drivers_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_morning_greeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_night_greeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
