# Generated by Django 6.0.7 on 2026-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0059_botsettings_last_evening_top_drivers_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='last_inactive_drivers_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_monthly_top_drivers_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_surge_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_weekly_top_drivers_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_driver_milestone',
            field=models.BooleanField(default=True, verbose_name='Haydovchi yubileyi (safarlar soni)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_inactive_drivers',
            field=models.BooleanField(default=True, verbose_name="Uzoq faol bo'lmagan haydovchilar hisoboti"),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_low_rating',
            field=models.BooleanField(default=True, verbose_name='Reyting pasayganda ogohlantirish'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_monthly_top_drivers',
            field=models.BooleanField(default=True, verbose_name='Oylik TOP-10 haydovchilar'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_sos_to_driver_group',
            field=models.BooleanField(default=True, verbose_name='SOS signalini haydovchilar guruhiga ham yuborish'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_surge_alert',
            field=models.BooleanField(default=True, verbose_name="Talab yuqori bo'lganda ogohlantirish"),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_weekly_top_drivers',
            field=models.BooleanField(default=True, verbose_name='Haftalik TOP-10 haydovchilar'),
        ),
    ]
