# Generated by Django 6.0.7 on 2026-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0060_botsettings_last_inactive_drivers_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='last_daily_highlight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_daily_summary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_high_rejection_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_top_hours_drivers_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_weekly_summary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_daily_highlight',
            field=models.BooleanField(default=True, verbose_name='Kunning yorqin lahzalari'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_daily_summary',
            field=models.BooleanField(default=True, verbose_name='Kunlik umumiy hisobot'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_flyer_redeemed',
            field=models.BooleanField(default=True, verbose_name='Flayer kuponi ishlatilganda xabar'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_high_rejection',
            field=models.BooleanField(default=True, verbose_name="Ko'p rad etish haqida ogohlantirish"),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_top_hours_drivers',
            field=models.BooleanField(default=True, verbose_name="Eng ko'p soat ishlagan haydovchilar"),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_weekly_summary',
            field=models.BooleanField(default=True, verbose_name='Haftalik umumiy hisobot'),
        ),
    ]
