# Generated by Django 6.0.7 on 2026-07-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0061_botsettings_last_daily_highlight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetopuprequest',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_monthly_financial_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_monthly_financial_report',
            field=models.BooleanField(default=True, verbose_name='Oylik moliyaviy hisobot'),
        ),
    ]
