# Generated by Django 6.0.7 on 2026-07-26 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0062_balancetopuprequest_reject_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('doc_type', models.CharField(choices=[('license', 'Litsenziya'), ('certificate', 'Guvohnoma'), ('other', 'Boshqa hujjat')], default='license', max_length=20, verbose_name='Turi')),
                ('number', models.CharField(blank=True, default='', max_length=100, verbose_name='Hujjat raqami')),
                ('file', models.FileField(upload_to='legal_docs/', verbose_name='Fayl')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Berilgan sana')),
                ('expires_at', models.DateField(blank=True, help_text="Muddatsiz bo'lsa bo'sh qoldiring", null=True, verbose_name='Amal qilish muddati')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
            ],
            options={
                'verbose_name': 'Yuridik hujjat',
                'verbose_name_plural': 'Yuridik hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Qisqa tavsif')),
                ('incident_type', models.CharField(choices=[('defamation', "Tuhmat / obro'ga putur"), ('blackmail', 'Shantaj / tahdid'), ('legal', 'Yuridik nizo / sud ishi'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='security_evidence/', verbose_name='Dalil (fayl/skrinshot)')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('investigating', 'Tekshirilmoqda'), ('resolved', 'Hal qilindi')], default='open', max_length=20, verbose_name='Holati')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='Hal qilish izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name="Kim ro'yxatga oldi")),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='taxi.client', verbose_name='Aloqador mijoz')),
                ('related_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='taxi.driver', verbose_name='Aloqador haydovchi')),
            ],
            options={
                'verbose_name': 'Xavfsizlik voqeasi',
                'verbose_name_plural': 'Xavfsizlik voqealari',
                'ordering': ['-created_at'],
            },
        ),
    ]
