# Generated by Django 6.0.7 on 2026-07-26 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0063_legaldocument_securityincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voiceparticipant',
            options={'verbose_name': 'Efirdagi ishtirokchi', 'verbose_name_plural': 'Efirdagi ishtirokchilar'},
        ),
        migrations.AddField(
            model_name='voiceparticipant',
            name='operator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_participant', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='voicesignal',
            name='from_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_signals_sent', to=settings.AUTH_USER_MODEL, verbose_name='Kimdan (operator)'),
        ),
        migrations.AddField(
            model_name='voicesignal',
            name='to_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_signals_received', to=settings.AUTH_USER_MODEL, verbose_name='Kimga (operator)'),
        ),
        migrations.AlterField(
            model_name='voiceparticipant',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_participant', to='taxi.driver', verbose_name='Haydovchi'),
        ),
        migrations.AlterField(
            model_name='voicesignal',
            name='from_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_signals_sent', to='taxi.driver', verbose_name='Kimdan (haydovchi)'),
        ),
        migrations.AlterField(
            model_name='voicesignal',
            name='to_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_signals_received', to='taxi.driver', verbose_name='Kimga (haydovchi)'),
        ),
        migrations.AddIndex(
            model_name='voicesignal',
            index=models.Index(fields=['to_operator', 'created_at'], name='taxi_voices_to_oper_7df690_idx'),
        ),
        migrations.AddConstraint(
            model_name='voiceparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('driver__isnull', False), ('operator__isnull', False), _connector='OR'), name='voice_participant_driver_or_operator'),
        ),
    ]
