# Generated by Django 4.2.16 on 2026-07-28 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0064_alter_voiceparticipant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyervoucher',
            name='owner_driver',
            field=models.ForeignKey(blank=True, help_text="Vizitka chop etilganda shu haydovchiga biriktirilgan bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vouchers', to='taxi.driver', verbose_name='Vizitka egasi'),
        ),
        migrations.CreateModel(
            name='VizitkaRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Hafta boshi')),
                ('voucher_count', models.PositiveIntegerField(default=0, verbose_name='Shu hafta tarqatilgan vizitkalar soni')),
                ('amount', models.DecimalField(decimal_places=0, default=100000, max_digits=10, verbose_name='Bonus summasi')),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizitka_rewards', to='taxi.driver')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vizitka reytingi bonusi',
                'verbose_name_plural': 'Vizitka reytingi bonuslari',
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='vizitkarewardlog',
            constraint=models.UniqueConstraint(fields=('driver', 'week_start'), name='unique_driver_vizitka_reward_per_week'),
        ),
    ]
