# Generated by Django 4.2.16 on 2026-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0065_flyervoucher_owner_driver_vizitkarewardlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='notify_deleted',
            field=models.BooleanField(default=True, verbose_name="Buyurtma o'chirildi"),
        ),
    ]
