# Generated by Django 4.2.16 on 2026-07-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0066_botsettings_notify_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Ogohlantirish'), ('error', 'Xato')], default='info', max_length=10, verbose_name='Daraja')),
                ('event_type', models.CharField(max_length=50, verbose_name='Hodisa turi')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Xabar')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Tafsilot (masalan traceback)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('path', models.CharField(blank=True, default='', max_length=300, verbose_name='Manzil (path)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tizim jurnali yozuvi',
                'verbose_name_plural': 'Tizim jurnali',
                'ordering': ['-created_at'],
            },
        ),
    ]
