# Generated by Django 4.2.16 on 2026-08-03 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0068_alter_panelsound_event_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_group_read_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name="Guruh chatini oxirgi o'qigan vaqt"),
        ),
    ]
