# Generated by Django 4.2.16 on 2026-08-03 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0069_driver_last_group_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Bozor, Aeroport, Markaziy stansiya', max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Manzil matni')),
                ('lat', models.FloatField(verbose_name='Kenglik')),
                ('lng', models.FloatField(verbose_name='Uzunlik')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan")),
            ],
            options={
                'verbose_name': 'Tezkor manzil',
                'verbose_name_plural': 'Tezkor manzillar',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
