# Generated by Django 4.2.16 on 2026-08-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0070_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='last_driver_engagement_evening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_driver_engagement_noon_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='last_driver_fun_stats_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_driver_engagement',
            field=models.BooleanField(default=True, verbose_name='Motivatsion/maslahat/hazil xabarlar'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_driver_fun_stats',
            field=models.BooleanField(default=True, verbose_name='Kunlik qiziqarli statistika'),
        ),
    ]
