# Generated by Django 4.2.16 on 2026-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0071_botsettings_last_driver_engagement_evening_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='notify_balance_changed_to_driver_group',
            field=models.BooleanField(default=True, verbose_name="Balans to'ldirilganda haydovchilar guruhiga ham yuborish"),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='notify_low_balance_to_driver_group',
            field=models.BooleanField(default=True, verbose_name='Balans kam qolganda haydovchilar guruhiga ham yuborish'),
        ),
    ]
