# Generated by Django 4.2.16 on 2026-08-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0072_botsettings_notify_balance_changed_to_driver_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_registered_orders', to='taxi.driver', verbose_name="Ilova orqali ro'yxatga olgan haydovchi"),
        ),
    ]
