# Generated by Django 4.2.16 on 2026-08-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0074_voicesignal_ratsiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsettings',
            name='office_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ofis Kenglik (Lat)'),
        ),
        migrations.AddField(
            model_name='tariffsettings',
            name='office_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Ofis Uzunlik (Lng)'),
        ),
        migrations.AddField(
            model_name='tariffsettings',
            name='office_name',
            field=models.CharField(blank=True, default='1351 Taxi ofisi', help_text="Haydovchilar xaritasidagi belgi tagida ko'rinadi", max_length=100, verbose_name='Ofis nomi'),
        ),
    ]
