# Generated by Django 4.2.16 on 2026-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0075_tariffsettings_office_lat_tariffsettings_office_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='last_freeze_inactive_drivers_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text="3+ kun onlayn bo'lmagani uchun avtomatik muzlatilgan — qayta ishga tushirish uchun admin blokni ochishi kerak", verbose_name='Muzlatilgan'),
        ),
        migrations.AlterField(
            model_name='driveractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('block', 'Bloklandi'), ('unblock', 'Blok ochildi'), ('balance', "Balans o'zgardi"), ('duty_on', 'Navbatga kirdi'), ('duty_off', 'Navbatdan chiqdi'), ('order', 'Buyurtma'), ('freeze', 'Muzlatildi'), ('unfreeze', 'Muzlash bekor qilindi')], max_length=20, verbose_name='Amal'),
        ),
    ]
