# Generated by Django 4.2.16 on 2026-08-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0076_botsettings_last_freeze_inactive_drivers_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bekor qilish sababi'),
        ),
    ]
