# Generated by Django 4.2.16 on 2026-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0077_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='last_order_creating_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Operator buyurtma yaratayotgani so'nggi bildirilgan vaqt"),
        ),
    ]
