# Generated by Django 4.2.16 on 2026-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0080_botsettings_last_freeze_warning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Mijoz botidan foydalansa avtomatik saqlanadi', max_length=50, verbose_name='Telegram chat ID'),
        ),
    ]
