# Generated by Django 4.2.16 on 2026-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0081_client_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='Yetkazib berish'),
        ),
    ]
