# Generated by Django 4.2.16 on 2026-08-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0082_order_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ping o'lchangan vaqt"),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_ping_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oxirgi ping (ms)'),
        ),
    ]
