# Generated by Django 4.2.16 on 2026-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0083_driver_last_ping_at_driver_last_ping_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsettings',
            name='fairness_weight_km',
            field=models.FloatField(default=1.5, help_text="Taqsimlashda haydovchining bugun olgan har bir buyurtmasi 'masofasiga' shuncha km qo'shib hisoblanadi — shu orqali kam buyurtma olgan haydovchi yaqinroq bo'lmasa ham ustunlik oladi. 0 = faqat masofa bo'yicha (adolat hisobga olinmaydi)", verbose_name='Adolat vazni (km)'),
        ),
    ]
