# Generated by Django 4.2.16 on 2026-08-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0084_tariffsettings_fairness_weight_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsettings',
            name='fairness_max_radius_km',
            field=models.FloatField(default=3.0, help_text="Shu radiusdan uzoqdagi haydovchilar avtomatik taqsimlashda umuman ko'rib chiqilmaydi — mijozni ortiqcha kutdirmaslik uchun (adolat mijoz tajribasidan ustun qo'yilmaydi). 0 = cheklovsiz", verbose_name='Adolat radiusi (km)'),
        ),
        migrations.AlterField(
            model_name='tariffsettings',
            name='fairness_weight_km',
            field=models.FloatField(default=1.2, help_text="Taqsimlashda haydovchining bugun yakunlagan har bir buyurtmasi 'masofasiga' shuncha km qo'shib hisoblanadi, uzoq kutgan haydovchining esa masofasi kamayadi (har 10 daqiqa kutish ≈ 1 km) — shu orqali band haydovchi hammasini olib ketmaydi. 0 = faqat masofa bo'yicha (adolat hisobga olinmaydi)", verbose_name='Adolat vazni (km)'),
        ),
    ]
