# Generated by Django 4.2.16 on 2026-08-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0085_tariffsettings_fairness_max_radius_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='Masofa (km)')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Urinish raqami')),
                ('result', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qildi'), ('rejected', 'Rad etdi'), ('timeout', 'Javob bermadi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Natija')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Taklif qilingan vaqt')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name="Hal bo'lgan vaqt")),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='taxi.driver', verbose_name='Haydovchi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='taxi.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Taqsimlash urinishi',
                'verbose_name_plural': 'Taqsimlash urinishlari',
                'ordering': ['attempt_number'],
            },
        ),
    ]
