# Generated by Django 4.2.16 on 2026-08-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0086_dispatchattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Navbatga kirgan vaqt')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Navbatdan chiqqan vaqt')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='taxi.savedaddress', verbose_name='Manzil')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_queue_entries', to='taxi.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Manzil navbati yozuvi',
                'verbose_name_plural': 'Manzil navbati yozuvlari',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['address', 'left_at'], name='taxi_addres_address_54f6ef_idx'), models.Index(fields=['driver', 'left_at'], name='taxi_addres_driver__f016cc_idx')],
            },
        ),
    ]
