# Generated by Django 4.2.16 on 2026-08-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0087_addressqueueentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('position', models.CharField(help_text='Masalan: Dispetcher, Buxgalter, Texnik xizmat', max_length=100, verbose_name='Lavozimi')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon raqami')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Rasm')),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ishga qabul qilingan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tizim akkaunti (ixtiyoriy)')),
            ],
            options={
                'verbose_name': 'Hodim',
                'verbose_name_plural': 'Hodimlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Vazifa')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('todo', 'Bajarilishi kerak'), ('in_progress', 'Jarayonda'), ('done', 'Bajarildi')], default='todo', max_length=20, verbose_name='Holati')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim topshirdi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taxi.employee', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Hodim vazifasi',
                'verbose_name_plural': 'Hodim vazifalari',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='taxi.employee', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Smena',
                'verbose_name_plural': 'Smena jadvali',
                'ordering': ['weekday'],
                'unique_together': {('employee', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Kelgan vaqti')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Ketgan vaqti')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('late', 'Kech qoldi'), ('absent', 'Kelmadi')], default='present', max_length=20, verbose_name='Holati')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='taxi.employee', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Davomat yozuvi',
                'verbose_name_plural': 'Davomat',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
