# Generated by Django 4.2.16 on 2026-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0089_alter_panelevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Telefon raqami')),
                ('audio', models.FileField(upload_to='call_recordings/%Y/%m/', verbose_name='Audio fayl')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': "Qo'ng'iroq yozuvi",
                'verbose_name_plural': "Qo'ng'iroq yozuvlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
