# Generated by Django 4.2.16 on 2026-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0090_callrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='battery_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Native ilova joylashuv yuborganda birga keladi', null=True, verbose_name='Batareya foizi'),
        ),
        migrations.AddField(
            model_name='driver',
            name='device_model',
            field=models.CharField(blank=True, default='', help_text="Native ilovaga kirganda avtomatik yoziladi (masalan 'Samsung SM-A125F')", max_length=120, verbose_name='Qurilma modeli'),
        ),
    ]
