# Generated by Django 4.2.16 on 2026-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0091_driver_battery_level_driver_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='pending_stand_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Kutilayotgan yangi manzil (kenglik)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pending_stand_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Kutilayotgan yangi manzil (uzunlik)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pending_stand_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shu nuqtada turgan vaqtdan beri'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='auto_created',
            field=models.BooleanField(default=False, help_text="Operator qo'lda emas, haydovchi shu nuqtada turgani sababli tizim tomonidan avtomatik yaratilgan", verbose_name='Avtomatik yaratilgan'),
        ),
    ]
