# Generated by Django 4.2.16 on 2026-08-11 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0094_seed_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercityRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Bitta o'rindiq narxi (so'm)")),
                ('seat_capacity', models.PositiveSmallIntegerField(default=4, verbose_name="Mashinadagi yo'lovchi o'rinlari")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercity_routes_from', to='taxi.region', verbose_name='Qayerdan (viloyat)')),
                ('to_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercity_routes_to', to='taxi.region', verbose_name='Qayerga (viloyat)')),
            ],
            options={
                'verbose_name': "Shahrlararo yo'nalish",
                'verbose_name_plural': "Shahrlararo yo'nalishlar",
                'ordering': ['from_region__order', 'to_region__order'],
                'unique_together': {('from_region', 'to_region')},
            },
        ),
        migrations.CreateModel(
            name='IntercityTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('filling', "Joy to'ldirilmoqda"), ('departed', "Jo'nab ketdi"), ('cancelled', 'Bekor qilindi')], default='filling', max_length=12, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Navbatga qo'shilgan vaqt")),
                ('departed_at', models.DateTimeField(blank=True, null=True, verbose_name="Jo'nagan vaqti")),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercity_trips', to='taxi.driver', verbose_name='Haydovchi')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='taxi.intercityroute', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Shahrlararo safar',
                'verbose_name_plural': 'Shahrlararo safarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntercitySeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name="Yo'lovchi ismi")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name="O'rindiqlar soni")),
                ('price', models.DecimalField(decimal_places=2, help_text='seats * IntercityRoute.seat_price (band qilingan paytdagi qiymat)', max_digits=10, verbose_name='Narx')),
                ('status', models.CharField(choices=[('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='confirmed', max_length=12, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Ro'yxatga olgan operator")),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='taxi.intercitytrip', verbose_name='Safar')),
            ],
            options={
                'verbose_name': "O'rindiq bandligi",
                'verbose_name_plural': "O'rindiq bandliklari",
                'ordering': ['created_at'],
            },
        ),
    ]
