# Generated by Django 4.2.16 on 2026-08-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0095_intercityroute_intercitytrip_intercityseatbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercityseatbooking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='intercityseatbooking',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='intercitytrip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='intercitytrip',
            name='route',
        ),
        migrations.DeleteModel(
            name='IntercityRoute',
        ),
        migrations.DeleteModel(
            name='IntercitySeatBooking',
        ),
        migrations.DeleteModel(
            name='IntercityTrip',
        ),
    ]
