# Generated by Django 4.2.16 on 2026-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0096_remove_intercity_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Yetib kelgan manzil'),
        ),
        migrations.AddField(
            model_name='order',
            name='arrived_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Yetib kelgan joy (Lat)'),
        ),
        migrations.AddField(
            model_name='order',
            name='arrived_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Yetib kelgan joy (Lng)'),
        ),
        migrations.AddField(
            model_name='order',
            name='on_way_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Yo'lga chiqqan manzil"),
        ),
        migrations.AddField(
            model_name='order',
            name='on_way_lat',
            field=models.FloatField(blank=True, null=True, verbose_name="Yo'lga chiqqan joy (Lat)"),
        ),
        migrations.AddField(
            model_name='order',
            name='on_way_lng',
            field=models.FloatField(blank=True, null=True, verbose_name="Yo'lga chiqqan joy (Lng)"),
        ),
    ]
