# Generated by Django 4.2.16 on 2026-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0097_order_on_way_arrived_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_qarzdor',
            field=models.BooleanField(default=False, verbose_name='Qarzdor'),
        ),
        migrations.AddField(
            model_name='driver',
            name='qarz_marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qarzdor deb belgilangan vaqt'),
        ),
        migrations.AddField(
            model_name='driver',
            name='qarz_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Qarz izohi'),
        ),
        migrations.AlterField(
            model_name='driveractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('block', 'Bloklandi'), ('unblock', 'Blok ochildi'), ('balance', "Balans o'zgardi"), ('duty_on', 'Navbatga kirdi'), ('duty_off', 'Navbatdan chiqdi'), ('order', 'Buyurtma'), ('freeze', 'Muzlatildi'), ('unfreeze', 'Muzlash bekor qilindi'), ('qarz_on', "Qarzdorlar ro'yxatiga qo'shildi"), ('qarz_off', "Qarzdorlar ro'yxatidan chiqarildi")], max_length=20, verbose_name='Amal'),
        ),
    ]
