# Generated by Django 4.2.16 on 2026-08-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0098_driver_is_qarzdor_driver_qarz_marked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicesignal',
            name='from_driver',
        ),
        migrations.RemoveField(
            model_name='voicesignal',
            name='from_operator',
        ),
        migrations.RemoveField(
            model_name='voicesignal',
            name='to_driver',
        ),
        migrations.RemoveField(
            model_name='voicesignal',
            name='to_operator',
        ),
        migrations.DeleteModel(
            name='VoiceParticipant',
        ),
        migrations.DeleteModel(
            name='VoiceSignal',
        ),
    ]
