# Generated by Django 4.2.16 on 2026-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0099_remove_voicesignal_from_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Kirish'), ('logout', 'Chiqish'), ('block', 'Bloklandi'), ('unblock', 'Blok ochildi'), ('balance', "Balans o'zgardi"), ('duty_on', 'Navbatga kirdi'), ('duty_off', 'Navbatdan chiqdi'), ('order', 'Buyurtma'), ('freeze', 'Muzlatildi'), ('unfreeze', 'Muzlash bekor qilindi'), ('qarz_on', "Qarzdorlar ro'yxatiga qo'shildi"), ('qarz_off', "Qarzdorlar ro'yxatidan chiqarildi"), ('qarz_note', 'Qarz izohi tahrirlandi')], max_length=20, verbose_name='Amal'),
        ),
    ]
