# Generated by Django 4.2.16 on 2026-08-14 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0100_alter_driveractivitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(verbose_name='FCM Token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Operator push tokeni',
                'verbose_name_plural': 'Operator push tokenlari',
                'unique_together': {('user', 'fcm_token')},
            },
        ),
    ]
