# Generated by Django 4.2.16 on 2026-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0101_operatorpushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('artist', models.CharField(blank=True, default='', max_length=150, verbose_name='Ijrochi')),
                ('file', models.FileField(blank=True, null=True, upload_to='music/', verbose_name='Audio fayl')),
                ('url', models.URLField(blank=True, default='', help_text='Fayl yuklanmasa, shu havoladan strim qilinadi', verbose_name='Tashqi havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichigi birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Musiqa',
                'verbose_name_plural': 'Musiqalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
