# Generated by Django 4.2.16 on 2026-08-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0102_musictrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssettings',
            name='provider',
            field=models.CharField(choices=[('eskiz', 'Eskiz.uz'), ('local_gateway', 'Telefon orqali (mahalliy SIM, vijdon_sms_gateway ilovasi)')], default='eskiz', help_text='"Telefon orqali" tanlansa, Eskiz.uz\'ga pul to\'lash shart emas — SMS\'lar vijdon_sms_gateway ilovasi o\'rnatilgan telefon(lar)ning oddiy SIM kartasi orqali yuboriladi. Diqqat: bu usul mobil operator tomonidan cheklanishi/bloklanishi mumkin — katta hajmda (kuniga yuzlab SMS) ehtiyot bo\'ling.', max_length=20, verbose_name='SMS xizmati'),
        ),
        migrations.CreateModel(
            name='SmsGatewayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(verbose_name='FCM Token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateway_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'SMS-shlyuz push tokeni',
                'verbose_name_plural': 'SMS-shlyuz push tokenlari',
                'unique_together': {('user', 'fcm_token')},
            },
        ),
        migrations.CreateModel(
            name='SmsGatewayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('text', models.TextField(verbose_name='Matn')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], default='pending', max_length=10, verbose_name='Holati')),
                ('error', models.CharField(blank=True, default='', max_length=255, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Band qilingan vaqti')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqti')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuborgan qurilma')),
            ],
            options={
                'verbose_name': 'SMS-shlyuz xabari',
                'verbose_name_plural': 'SMS-shlyuz xabarlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='taxi_smsgat_status_e353d2_idx')],
            },
        ),
    ]
