# Generated by Django 4.2.16 on 2026-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0103_smssettings_provider_smsgatewaytoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='low_balance_sms_at',
            field=models.DateTimeField(blank=True, help_text='Har buyurtma qabul qilganda emas, bir necha soatda bir marta SMS yuborilishi uchun (utils.tg_low_balance_alert)', null=True, verbose_name="Oxirgi 'balans kam' SMS vaqti"),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='sms_driver_cancelled',
            field=models.BooleanField(default=True, verbose_name='Haydovchiga: buyurtma bekor qilindi/qayta ochildi'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='sms_driver_low_balance',
            field=models.BooleanField(default=True, verbose_name='Haydovchiga: balans kam qoldi'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='sms_driver_new_order',
            field=models.BooleanField(default=False, help_text="Diqqat: bu har bir tayinlangan buyurtmada yuboriladi — push allaqachon bor, shu sabab sukut bo'yicha O'CHIQ (katta hajm SIM-blok xavfini oshiradi).", verbose_name='Haydovchiga: yangi buyurtma (zaxira)'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='sms_driver_topup_approved',
            field=models.BooleanField(default=True, verbose_name="Haydovchiga: to'lov tasdiqlandi"),
        ),
    ]
