# Generated by Django 4.2.16 on 2026-08-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0104_driver_low_balance_sms_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsGatewayIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Kimdan')),
                ('text', models.TextField(verbose_name='Matn')),
                ('received_at', models.DateTimeField(verbose_name='Qurilmada qabul qilingan vaqt')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Serverga tushgan vaqt')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sms_messages', to=settings.AUTH_USER_MODEL, verbose_name='Qaysi qurilma')),
            ],
            options={
                'verbose_name': 'Kelgan SMS',
                'verbose_name_plural': 'Kelgan SMS xabarlari',
                'ordering': ['-received_at'],
            },
        ),
    ]
