# Generated by Django 4.2.16 on 2026-08-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0105_smsgatewayincoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('text', models.TextField(max_length=480, verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'SMS shabloni',
                'verbose_name_plural': 'SMS shablonlari',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='sms_opt_out',
            field=models.BooleanField(default=False, help_text='"BEKOR" deb SMS javob yozsa avtomatik yoqiladi — buyurtma holati SMS\'lariga ta\'sir qilmaydi, faqat ommaviy xabarlar to\'xtaydi', verbose_name="Ommaviy SMS'lardan chiqqan"),
        ),
        migrations.AddField(
            model_name='driver',
            name='sms_opt_out',
            field=models.BooleanField(default=False, help_text='"BEKOR" deb SMS javob yozsa avtomatik yoqiladi — buyurtma/balans SMS\'lariga ta\'sir qilmaydi, faqat ommaviy xabarlar to\'xtaydi', verbose_name="Ommaviy SMS'lardan chiqqan"),
        ),
    ]
