# Generated by Django 4.2.16 on 2026-08-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0106_smstemplate_client_sms_opt_out_driver_sms_opt_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsTemplate',
        ),
    ]
