# Generated by Django 4.2.16 on 2026-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0107_delete_smstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='chat_ai_enabled',
            field=models.BooleanField(default=True, help_text="Yoqilsa, haydovchi ilovasidagi Chat bo'limida AI avtomatik javob beradi", verbose_name='Chatda AI javob bersin'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('driver', 'Haydovchi'), ('operator', 'Operator'), ('ai', 'AI yordamchi')], max_length=10, verbose_name='Kimdan'),
        ),
    ]
