# Generated by Django 4.2.16 on 2026-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0108_aisettings_chat_ai_enabled_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ai_typing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI yordamchi javob tayyorlayotgan vaqt'),
        ),
    ]
