# Generated by Django 4.2.16 on 2026-08-16 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0109_driver_ai_typing_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', "Yoqilg'i"), ('salary', 'Xodimlar maoshi'), ('bonus', 'Haydovchi bonusi/mukofot'), ('rent', 'Ijaraga/ofis'), ('marketing', 'Reklama/marketing'), ('maintenance', "Texnik xizmat/ta'mirlash"), ('communication', 'SMS/aloqa xizmatlari'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Chek/hujjat')),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
    ]
