# Generated by Django 4.2.16 on 2026-08-16 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0110_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='notify_goal_events',
            field=models.BooleanField(default=True, verbose_name='Maqsadga erishilganda/muddat yaqinlashganda xabar'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('metric', models.CharField(choices=[('revenue', "Komissiya daromadi (so'm)"), ('orders', 'Yakunlangan buyurtmalar soni'), ('new_drivers', "Yangi ro'yxatdan o'tgan haydovchilar"), ('active_clients', 'Faol mijozlar soni (buyurtma bergan)'), ('custom', "Qo'lda kiritiladi")], default='custom', max_length=20, verbose_name="O'lchov turi")),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Maqsad qiymati')),
                ('manual_value', models.DecimalField(decimal_places=2, default=0, help_text='Faqat "Qo\'lda kiritiladi" turi uchun — boshqa turlar avtomatik hisoblanadi', max_digits=14, verbose_name="Joriy qiymat (qo'lda)")),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Boshlanish sanasi')),
                ('deadline', models.DateField(verbose_name='Tugash muddati')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Erishildi'), ('failed', "Muddati o'tdi")], default='active', max_length=12, verbose_name='Holati')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erishilgan vaqt')),
                ('notified_completed', models.BooleanField(default=False)),
                ('notified_deadline_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsadlar',
                'ordering': ['status', 'deadline'],
            },
        ),
    ]
