# Generated by Django 4.2.16 on 2026-08-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0111_botsettings_notify_goal_events_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quick_address_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxi.district', verbose_name='Tezkor manzil — oxirgi tuman')),
                ('quick_address_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxi.region', verbose_name='Tezkor manzil — oxirgi viloyat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_preference', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Operator sozlamasi',
                'verbose_name_plural': 'Operator sozlamalari',
            },
        ),
    ]
