# Generated by Django 4.2.16 on 2026-08-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0112_operatorpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicTrack',
        ),
    ]
